// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos; // Changed to use macos configuration
      case TargetPlatform.windows:
        return windows; // Changed to use windows configuration
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6olYrAFwy0MgJiKZ17vMebRxdAoUvxbk',
    appId: '1:542835994680:web:a707c817e08b7354ba36cd',
    messagingSenderId: '542835994680',
    projectId: 'greentransport-kwy',
    authDomain: 'greentransport-kwy.firebaseapp.com',
    storageBucket: 'greentransport-kwy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaE3VMfX9m9aSlTxC_X0DjDYRTlqhsF0',
    appId: '1:542835994680:android:aa93b7c3b77c41a7ba36cd',
    messagingSenderId: '542835994680',
    projectId: 'greentransport-kwy',
    storageBucket: 'greentransport-kwy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfJfZd0F9rldBxKsigQRkPP-IwGlOaFw',
    appId: '1:542835994680:ios:a3e1d3879fc2cbdeba36cd',
    messagingSenderId: '542835994680',
    projectId: 'greentransport-kwy',
    storageBucket: 'greentransport-kwy.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions( // Using Android config for macOS for now
    apiKey: 'AIzaSyBmaE3VMfX9m9aSlTxC_X0DjDYRTlqhsF0',
    appId: '1:542835994680:android:aa93b7c3b77c41a7ba36cd',
    messagingSenderId: '542835994680',
    projectId: 'greentransport-kwy',
    storageBucket: 'greentransport-kwy.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions( // Using Web config for Windows for now
    apiKey: 'AIzaSyB6olYrAFwy0MgJiKZ17vMebRxdAoUvxbk',
    appId: '1:542835994680:web:7d37cc15f06cee29ba36cd',
    messagingSenderId: '542835994680',
    projectId: 'greentransport-kwy',
    authDomain: 'greentransport-kwy.firebaseapp.com',
    storageBucket: 'greentransport-kwy.firebasestorage.app',
  );
}